[workspace]
members = ["crates/natmap"]

[package]
name = "lab-ops"
version = "0.1.0"
edition = "2024"

[features]
docker-tests = []

[dependencies]
regex = "1.12.3"
clap = { version = "4", features = ["derive"] }
bollard = "0.21.0"
color-eyre = "0.6.5"
comfy-table = "7.2.2"
tokio = { version = "1.52.2", features = ["rt"] }
natmap = { path = "./crates/natmap" }

[lints.clippy]
uninlined_format_args = "deny"
new_without_default = "allow"
