[workspace]
members = ["crates/natmap", "crates/auto-discover", "crates/lab-lib"]

[package]
name = "lab-ops"
version = "0.1.12"
edition = "2024"

[features]
docker-tests = []

[dependencies]
regex = "1.12.3"
clap = { version = "4", features = ["derive"] }
bollard = "0.21.0"
color-eyre = "0.6.5"
comfy-table = "7.2.2"
tokio = { version = "1.52.2", features = ["rt"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
lab-lib = { path = "./crates/lab-lib" }
natmap = { path = "./crates/natmap" }
auto-discover = { path = "./crates/auto-discover" }

[lints.clippy]
uninlined_format_args = "warn"
new_without_default = "allow"
